version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MY-PORTFOLIO"
s3_bucket = "MY_PORTFOLIO_BUCKET"
s3_prefix = "MY-PORTFOLIO"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
disable_rollback = true
image_repositories = []
