AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  DatabaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DBLayer
      Description: A layer for setting up database connection
      ContentUri: layers/utils/
      CompatibleRuntimes:
        - python3.11
  GetMyBasicInformationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: info/get_basic_info/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - !Ref DatabaseLayer
      Architectures:
        - x86_64
      Events:
        GetBasicInfo:
          Type: Api
          Properties:
            Path: /get_basic_info
            Method: get
